create table if not exists public.promotion_tesco_category_mappings (
  category_key text primary key,
  tesco_category text not null,
  level_1 text not null,
  updated_at timestamptz not null default now(),
  constraint promotion_tesco_category_mappings_level_1_check check (
    level_1 in ('Baby', 'BWS', 'Celebration', 'Electricals', 'Health & Beauty',
                'Home', 'Outdoor', 'Pet', 'Sports & Leisure', 'Toys')
  )
);

alter table public.promotion_tesco_category_mappings enable row level security;

grant select, insert, update, delete
  on public.promotion_tesco_category_mappings
  to service_role;
revoke all
  on public.promotion_tesco_category_mappings
  from anon, authenticated;

insert into public.promotion_tesco_category_mappings
  (category_key, tesco_category, level_1)
values
  ('animals & pet supplies/pet supplies/cat supplies/cat furniture/cat condos & houses', 'Animals & Pet Supplies/Pet Supplies/Cat Supplies/Cat Furniture/Cat Condos & Houses', 'Pet'),
  ('animals & pet supplies/pet supplies/cat supplies/cat furniture/cat perches & shelves', 'Animals & Pet Supplies/Pet Supplies/Cat Supplies/Cat Furniture/Cat Perches & Shelves', 'Pet'),
  ('animals & pet supplies/pet supplies/cat supplies/cat furniture/cat scratchers & scratching posts', 'Animals & Pet Supplies/Pet Supplies/Cat Supplies/Cat Furniture/Cat Scratchers & Scratching Posts', 'Pet'),
  ('animals & pet supplies/pet supplies/cat supplies/cat furniture/cat trees & towers', 'Animals & Pet Supplies/Pet Supplies/Cat Supplies/Cat Furniture/Cat Trees & Towers', 'Pet'),
  ('animals & pet supplies/pet supplies/cat supplies/cat litter/cat litter box liners', 'Animals & Pet Supplies/Pet Supplies/Cat Supplies/Cat Litter/Cat Litter Box Liners', 'Pet'),
  ('animals & pet supplies/pet supplies/cat supplies/cat litter/cat litter boxes', 'Animals & Pet Supplies/Pet Supplies/Cat Supplies/Cat Litter/Cat Litter Boxes', 'Pet'),
  ('animals & pet supplies/pet supplies/cat supplies/cat toys/tunnels', 'Animals & Pet Supplies/Pet Supplies/Cat Supplies/Cat Toys/Tunnels', 'Pet'),
  ('animals & pet supplies/pet supplies/dog supplies/dog diaper pads & liners', 'Animals & Pet Supplies/Pet Supplies/Dog Supplies/Dog Diaper Pads & Liners', 'Pet'),
  ('animals & pet supplies/pet supplies/dog supplies/dog houses', 'Animals & Pet Supplies/Pet Supplies/Dog Supplies/Dog Houses', 'Pet'),
  ('animals & pet supplies/pet supplies/dog supplies/dog kennel & run accessories', 'Animals & Pet Supplies/Pet Supplies/Dog Supplies/Dog Kennel & Run Accessories', 'Pet'),
  ('animals & pet supplies/pet supplies/dog supplies/dog kennels & runs/dog pens', 'Animals & Pet Supplies/Pet Supplies/Dog Supplies/Dog Kennels & Runs/Dog Pens', 'Pet'),
  ('animals & pet supplies/pet supplies/dog supplies/dog kennels & runs/indoor dog kennels', 'Animals & Pet Supplies/Pet Supplies/Dog Supplies/Dog Kennels & Runs/Indoor Dog Kennels', 'Pet'),
  ('animals & pet supplies/pet supplies/pet beds/bolster beds', 'Animals & Pet Supplies/Pet Supplies/Pet Beds/Bolster Beds', 'Pet'),
  ('animals & pet supplies/pet supplies/pet beds/donuts', 'Animals & Pet Supplies/Pet Supplies/Pet Beds/Donuts', 'Pet'),
  ('animals & pet supplies/pet supplies/pet beds/nests', 'Animals & Pet Supplies/Pet Supplies/Pet Beds/Nests', 'Pet'),
  ('animals & pet supplies/pet supplies/pet beds/orthopaedic beds', 'Animals & Pet Supplies/Pet Supplies/Pet Beds/Orthopaedic Beds', 'Pet'),
  ('animals & pet supplies/pet supplies/pet beds/pillow beds', 'Animals & Pet Supplies/Pet Supplies/Pet Beds/Pillow Beds', 'Pet'),
  ('animals & pet supplies/pet supplies/pet bowls, feeders & waterers/automatic feeders', 'Animals & Pet Supplies/Pet Supplies/Pet Bowls, Feeders & Waterers/Automatic Feeders', 'Pet'),
  ('animals & pet supplies/pet supplies/pet bowls, feeders & waterers/bowls', 'Animals & Pet Supplies/Pet Supplies/Pet Bowls, Feeders & Waterers/Bowls', 'Pet'),
  ('animals & pet supplies/pet supplies/pet carriers & crates/car crates', 'Animals & Pet Supplies/Pet Supplies/Pet Carriers & Crates/Car Crates', 'Pet'),
  ('animals & pet supplies/pet supplies/pet carriers & crates/soft-sided carriers', 'Animals & Pet Supplies/Pet Supplies/Pet Carriers & Crates/Soft-Sided Carriers', 'Pet'),
  ('animals & pet supplies/pet supplies/pet containment systems/fences & gates', 'Animals & Pet Supplies/Pet Supplies/Pet Containment Systems/Fences & Gates', 'Pet'),
  ('animals & pet supplies/pet supplies/pet grooming supplies/pet combs & brushes/groomers', 'Animals & Pet Supplies/Pet Supplies/Pet Grooming Supplies/Pet Combs & Brushes/Groomers', 'Pet'),
  ('animals & pet supplies/pet supplies/pet grooming supplies/pet hair clippers & trimmers/trimmers', 'Animals & Pet Supplies/Pet Supplies/Pet Grooming Supplies/Pet Hair Clippers & Trimmers/Trimmers', 'Pet'),
  ('animals & pet supplies/pet supplies/pet steps & ramps', 'Animals & Pet Supplies/Pet Supplies/Pet Steps & Ramps', 'Pet'),
  ('animals & pet supplies/pet supplies/pet strollers/standard strollers', 'Animals & Pet Supplies/Pet Supplies/Pet Strollers/Standard Strollers', 'Pet'),
  ('animals & pet supplies/pet supplies/small animal supplies/small animal habitats & cages', 'Animals & Pet Supplies/Pet Supplies/Small Animal Supplies/Small Animal Habitats & Cages', 'Pet'),
  ('animals & pet supplies/pet supplies/vehicle pet barriers/backseat barriers', 'Animals & Pet Supplies/Pet Supplies/Vehicle Pet Barriers/Backseat Barriers', 'Pet'),
  ('arts & entertainment/hobbies & creative arts/arts & crafts/art & crafting tools/textile craft machines/sewing machines/mechanical sewing machines', 'Arts & Entertainment/Hobbies & Creative Arts/Arts & Crafts/Art & Crafting Tools/Textile Craft Machines/Sewing Machines/Mechanical Sewing Machines', 'Home'),
  ('arts & entertainment/party & celebration/party supplies/party supply kits', 'Arts & Entertainment/Party & Celebration/Party Supplies/Party Supply Kits', 'Celebration'),
  ('baby & toddler/baby health/pacifiers & teethers/pacifiers', 'Baby & Toddler/Baby Health/Pacifiers & Teethers/Pacifiers', 'Baby'),
  ('baby & toddler/baby toys & activity equipment/baby activity toys/activity centres', 'Baby & Toddler/Baby Toys & Activity Equipment/Baby Activity Toys/Activity Centres', 'Baby'),
  ('baby & toddler/baby toys & activity equipment/play mats & gyms/play mats', 'Baby & Toddler/Baby Toys & Activity Equipment/Play Mats & Gyms/Play Mats', 'Baby'),
  ('baby & toddler/baby toys & activity equipment/play yards', 'Baby & Toddler/Baby Toys & Activity Equipment/Play Yards', 'Baby'),
  ('baby & toddler/baby transport accessories/baby & toddler car seat accessories/car seat covers', 'Baby & Toddler/Baby Transport Accessories/Baby & Toddler Car Seat Accessories/Car Seat Covers', 'Baby'),
  ('baby & toddler/diapering/diaper kits/diaper bag kits', 'Baby & Toddler/Diapering/Diaper Kits/Diaper Bag Kits', 'Baby'),
  ('baby & toddler/nursing & feeding/bottle warmers & sterilisers/sterilisers/electric steam sterilisers', 'Baby & Toddler/Nursing & Feeding/Bottle Warmers & Sterilisers/Sterilisers/Electric Steam Sterilisers', 'Baby'),
  ('baby & toddler/nursing & feeding/nursing pillows', 'Baby & Toddler/Nursing & Feeding/Nursing Pillows', 'Baby'),
  ('baby & toddler/potty training/potties', 'Baby & Toddler/Potty Training/Potties', 'Baby'),
  ('baby & toddler/potty training/toilet seats & step stools', 'Baby & Toddler/Potty Training/Toilet Seats & Step Stools', 'Baby'),
  ('business & industrial/law enforcement/metal detectors', 'Business & Industrial/Law Enforcement/Metal Detectors', 'Outdoor'),
  ('cameras & optics/cameras/surveillance cameras', 'Cameras & Optics/Cameras/Surveillance Cameras', 'Electricals'),
  ('cameras & optics/optics/binoculars', 'Cameras & Optics/Optics/Binoculars', 'Sports & Leisure'),
  ('electronics/electronics accessories/computer accessories/computer risers & stands', 'Electronics/Electronics Accessories/Computer Accessories/Computer Risers & Stands', 'Electricals'),
  ('electronics/electronics accessories/power/power stations', 'Electronics/Electronics Accessories/Power/Power Stations', 'Electricals'),
  ('furniture/baby & toddler furniture/baby & toddler furniture sets', 'Furniture/Baby & Toddler Furniture/Baby & Toddler Furniture Sets', 'Baby'),
  ('furniture/baby & toddler furniture/high chairs & booster seats/high chairs', 'Furniture/Baby & Toddler Furniture/High Chairs & Booster Seats/High Chairs', 'Baby'),
  ('furniture/beds & accessories/bed & bed frame accessories', 'Furniture/Beds & Accessories/Bed & Bed Frame Accessories', 'Home'),
  ('furniture/beds & accessories/beds & bed frames/panel beds & bed frames', 'Furniture/Beds & Accessories/Beds & Bed Frames/Panel Beds & Bed Frames', 'Home'),
  ('furniture/beds & accessories/beds & bed frames/slat beds & bed frames', 'Furniture/Beds & Accessories/Beds & Bed Frames/Slat Beds & Bed Frames', 'Home'),
  ('furniture/beds & accessories/beds & bed frames/trundle beds & bed frames', 'Furniture/Beds & Accessories/Beds & Bed Frames/Trundle Beds & Bed Frames', 'Home'),
  ('furniture/beds & accessories/mattresses/innerspring mattresses', 'Furniture/Beds & Accessories/Mattresses/Innerspring Mattresses', 'Home'),
  ('furniture/benches/storage & entryway benches/coat racks', 'Furniture/Benches/Storage & Entryway Benches/Coat Racks', 'Home'),
  ('furniture/benches/storage & entryway benches/shoe storage benches', 'Furniture/Benches/Storage & Entryway Benches/Shoe Storage Benches', 'Home'),
  ('furniture/benches/vanity benches', 'Furniture/Benches/Vanity Benches', 'Home'),
  ('furniture/cabinets & storage/armoires & wardrobes/tv armoires', 'Furniture/Cabinets & Storage/Armoires & Wardrobes/TV Armoires', 'Home'),
  ('furniture/cabinets & storage/dressers', 'Furniture/Cabinets & Storage/Dressers', 'Home'),
  ('furniture/cabinets & storage/file cabinets', 'Furniture/Cabinets & Storage/File Cabinets', 'Home'),
  ('furniture/cabinets & storage/magazine racks', 'Furniture/Cabinets & Storage/Magazine Racks', 'Home'),
  ('furniture/cabinets & storage/storage cabinets & lockers', 'Furniture/Cabinets & Storage/Storage Cabinets & Lockers', 'Home'),
  ('furniture/cabinets & storage/vanities/bathroom vanities/bathroom cabinets', 'Furniture/Cabinets & Storage/Vanities/Bathroom Vanities/Bathroom Cabinets', 'Home'),
  ('furniture/cabinets & storage/vanities/bedroom vanities/dressing tables', 'Furniture/Cabinets & Storage/Vanities/Bedroom Vanities/Dressing Tables', 'Home'),
  ('furniture/cabinets & storage/vanities/bedroom vanities/makeup vanities', 'Furniture/Cabinets & Storage/Vanities/Bedroom Vanities/Makeup Vanities', 'Home'),
  ('furniture/cabinets & storage/wine racks', 'Furniture/Cabinets & Storage/Wine Racks', 'Home'),
  ('furniture/carts & islands/carts', 'Furniture/Carts & Islands/Carts', 'Home'),
  ('furniture/chairs/kitchen & dining room chairs', 'Furniture/Chairs/Kitchen & Dining Room Chairs', 'Home'),
  ('furniture/chairs/table & bar stools/adjustable bar stools', 'Furniture/Chairs/Table & Bar Stools/Adjustable Bar Stools', 'Home'),
  ('furniture/entertainment centres & tv stands', 'Furniture/Entertainment Centres & TV Stands', 'Home'),
  ('furniture/furniture sets/bathroom furniture sets', 'Furniture/Furniture Sets/Bathroom Furniture Sets', 'Home'),
  ('furniture/furniture sets/bedroom furniture sets', 'Furniture/Furniture Sets/Bedroom Furniture Sets', 'Home'),
  ('furniture/furniture sets/kitchen & dining furniture sets', 'Furniture/Furniture Sets/Kitchen & Dining Furniture Sets', 'Home'),
  ('furniture/office furniture accessories/desk parts & accessories', 'Furniture/Office Furniture Accessories/Desk Parts & Accessories', 'Home'),
  ('furniture/office furniture/desks', 'Furniture/Office Furniture/Desks', 'Home'),
  ('furniture/office furniture/office chairs', 'Furniture/Office Furniture/Office Chairs', 'Home'),
  ('furniture/outdoor furniture accessories/outdoor furniture covers', 'Furniture/Outdoor Furniture Accessories/Outdoor Furniture Covers', 'Outdoor'),
  ('furniture/outdoor furniture/outdoor seating/outdoor benches/picnic benches', 'Furniture/Outdoor Furniture/Outdoor Seating/Outdoor Benches/Picnic Benches', 'Outdoor'),
  ('furniture/outdoor furniture/outdoor seating/outdoor chairs/folding chairs', 'Furniture/Outdoor Furniture/Outdoor Seating/Outdoor Chairs/Folding Chairs', 'Outdoor'),
  ('furniture/outdoor furniture/outdoor seating/outdoor sofas/sectional sofas', 'Furniture/Outdoor Furniture/Outdoor Seating/Outdoor Sofas/Sectional Sofas', 'Outdoor'),
  ('furniture/outdoor furniture/outdoor tables/dining tables', 'Furniture/Outdoor Furniture/Outdoor Tables/Dining Tables', 'Outdoor'),
  ('furniture/outdoor furniture/outdoor tables/fire pits', 'Furniture/Outdoor Furniture/Outdoor Tables/Fire Pits', 'Outdoor'),
  ('furniture/shelving/bookcases & standing shelves/corner bookcases & shelves', 'Furniture/Shelving/Bookcases & Standing Shelves/Corner Bookcases & Shelves', 'Home'),
  ('furniture/shelving/bookcases & standing shelves/floating bookcases & shelves', 'Furniture/Shelving/Bookcases & Standing Shelves/Floating Bookcases & Shelves', 'Home'),
  ('furniture/shelving/bookcases & standing shelves/rack bookcases & shelves', 'Furniture/Shelving/Bookcases & Standing Shelves/Rack Bookcases & Shelves', 'Home'),
  ('furniture/shelving/wall shelves & ledges/floating wall shelves & ledges', 'Furniture/Shelving/Wall Shelves & Ledges/Floating Wall Shelves & Ledges', 'Home'),
  ('furniture/sofas/corner sofas', 'Furniture/Sofas/Corner Sofas', 'Home'),
  ('furniture/sofas/loveseat sofas', 'Furniture/Sofas/Loveseat Sofas', 'Home'),
  ('furniture/tables/accent tables/coffee tables', 'Furniture/Tables/Accent Tables/Coffee Tables', 'Home'),
  ('furniture/tables/accent tables/end tables', 'Furniture/Tables/Accent Tables/End Tables', 'Home'),
  ('furniture/tables/accent tables/sofa tables', 'Furniture/Tables/Accent Tables/Sofa Tables', 'Home'),
  ('furniture/tables/nightstands', 'Furniture/Tables/Nightstands', 'Home'),
  ('hardware/fencing & barriers/fence posts & rails/end posts', 'Hardware/Fencing & Barriers/Fence Posts & Rails/End Posts', 'Outdoor'),
  ('hardware/fencing & barriers/garden borders & edging/border fences', 'Hardware/Fencing & Barriers/Garden Borders & Edging/Border Fences', 'Outdoor'),
  ('hardware/fencing & barriers/garden borders & edging/edging', 'Hardware/Fencing & Barriers/Garden Borders & Edging/Edging', 'Outdoor'),
  ('hardware/hardware accessories/hardware fasteners/drywall anchors', 'Hardware/Hardware Accessories/Hardware Fasteners/Drywall Anchors', 'Home'),
  ('hardware/hardware accessories/tool storage & organisation/tool cabinets & chests/rolling cabinets & chests', 'Hardware/Hardware Accessories/Tool Storage & Organisation/Tool Cabinets & Chests/Rolling Cabinets & Chests', 'Home'),
  ('hardware/hardware accessories/wall jacks & braces', 'Hardware/Hardware Accessories/Wall Jacks & Braces', 'Home'),
  ('hardware/plumbing/plumbing fixtures/toilets & bidets/toilets/one-piece toilets', 'Hardware/Plumbing/Plumbing Fixtures/Toilets & Bidets/Toilets/One-Piece Toilets', 'Home'),
  ('hardware/tools/compressors', 'Hardware/Tools/Compressors', 'Home'),
  ('hardware/tools/drills/handheld power drills/hammer drills', 'Hardware/Tools/Drills/Handheld Power Drills/Hammer Drills', 'Home'),
  ('hardware/tools/drills/handheld power drills/impact drills', 'Hardware/Tools/Drills/Handheld Power Drills/Impact Drills', 'Home'),
  ('hardware/tools/drills/pneumatic drills/pistol grip drills', 'Hardware/Tools/Drills/Pneumatic Drills/Pistol Grip Drills', 'Home'),
  ('hardware/tools/grinders/angle grinders', 'Hardware/Tools/Grinders/Angle Grinders', 'Home'),
  ('hardware/tools/heat guns/hot air guns', 'Hardware/Tools/Heat Guns/Hot Air Guns', 'Home'),
  ('hardware/tools/impact wrenches & drivers/power screwdrivers', 'Hardware/Tools/Impact Wrenches & Drivers/Power Screwdrivers', 'Home'),
  ('hardware/tools/ladders & scaffolding/ladders/step ladders', 'Hardware/Tools/Ladders & Scaffolding/Ladders/Step Ladders', 'Home'),
  ('hardware/tools/ladders & scaffolding/step stools', 'Hardware/Tools/Ladders & Scaffolding/Step Stools', 'Home'),
  ('hardware/tools/measuring tools & sensors/gauges/pressure gauges', 'Hardware/Tools/Measuring Tools & Sensors/Gauges/Pressure Gauges', 'Home'),
  ('hardware/tools/measuring tools & sensors/levels/laser levels/line & combi laser levels', 'Hardware/Tools/Measuring Tools & Sensors/Levels/Laser Levels/Line & Combi Laser Levels', 'Home'),
  ('hardware/tools/paint tools/paint sprayers/hvlp sprayers', 'Hardware/Tools/Paint Tools/Paint Sprayers/HVLP Sprayers', 'Home'),
  ('hardware/tools/polishers & buffers/rotary polishers & buffers', 'Hardware/Tools/Polishers & Buffers/Rotary Polishers & Buffers', 'Home'),
  ('hardware/tools/riveting tools/rivet pliers', 'Hardware/Tools/Riveting Tools/Rivet Pliers', 'Home'),
  ('hardware/tools/saws/reciprocating saws', 'Hardware/Tools/Saws/Reciprocating Saws', 'Home'),
  ('hardware/tools/wrenches/socket wrenches', 'Hardware/Tools/Wrenches/Socket Wrenches', 'Home'),
  ('health & beauty/health care/biometric monitors/body weight scales', 'Health & Beauty/Health Care/Biometric Monitors/Body Weight Scales', 'Health & Beauty'),
  ('health & beauty/health care/mobility & accessibility/accessibility equipment accessories', 'Health & Beauty/Health Care/Mobility & Accessibility/Accessibility Equipment Accessories', 'Health & Beauty'),
  ('health & beauty/health care/mobility & accessibility/accessibility furniture & fixtures/shower benches & seats/shower seats', 'Health & Beauty/Health Care/Mobility & Accessibility/Accessibility Furniture & Fixtures/Shower Benches & Seats/Shower Seats', 'Health & Beauty'),
  ('health & beauty/health care/supports & braces/elbow supports', 'Health & Beauty/Health Care/Supports & Braces/Elbow Supports', 'Health & Beauty'),
  ('health & beauty/jewellery cleaning & care/jewellery holders/jewellery boxes', 'Health & Beauty/Jewellery Cleaning & Care/Jewellery Holders/Jewellery Boxes', 'Health & Beauty'),
  ('health & beauty/personal care/cosmetics/cosmetic tools/makeup tools/face mirrors', 'Health & Beauty/Personal Care/Cosmetics/Cosmetic Tools/Makeup Tools/Face Mirrors', 'Health & Beauty'),
  ('health & beauty/personal care/cosmetics/cosmetic tools/makeup tools/refillable makeup palettes & cases', 'Health & Beauty/Personal Care/Cosmetics/Cosmetic Tools/Makeup Tools/Refillable Makeup Palettes & Cases', 'Health & Beauty'),
  ('health & beauty/personal care/cosmetics/skin care/face moisturisers', 'Health & Beauty/Personal Care/Cosmetics/Skin Care/Face Moisturisers', 'Health & Beauty'),
  ('health & beauty/personal care/cosmetics/skin care/lotions & moisturisers', 'Health & Beauty/Personal Care/Cosmetics/Skin Care/Lotions & Moisturisers', 'Health & Beauty'),
  ('health & beauty/personal care/hair care/hair dye', 'Health & Beauty/Personal Care/Hair Care/Hair Dye', 'Health & Beauty'),
  ('health & beauty/personal care/hair care/shampoo & conditioner/shampoo', 'Health & Beauty/Personal Care/Hair Care/Shampoo & Conditioner/Shampoo', 'Health & Beauty'),
  ('health & beauty/personal care/massage & relaxation/massagers/electric massagers', 'Health & Beauty/Personal Care/Massage & Relaxation/Massagers/Electric Massagers', 'Health & Beauty'),
  ('health & beauty/personal care/oral care/dental floss', 'Health & Beauty/Personal Care/Oral Care/Dental Floss', 'Health & Beauty'),
  ('home & garden/bathroom accessories/bath mats & rugs', 'Home & Garden/Bathroom Accessories/Bath Mats & Rugs', 'Home'),
  ('home & garden/bathroom accessories/safety grab bars', 'Home & Garden/Bathroom Accessories/Safety Grab Bars', 'Home'),
  ('home & garden/bathroom accessories/towel racks & holders/towel racks', 'Home & Garden/Bathroom Accessories/Towel Racks & Holders/Towel Racks', 'Home'),
  ('home & garden/business & home security/security safes/fireproof safes', 'Home & Garden/Business & Home Security/Security Safes/Fireproof Safes', 'Home'),
  ('home & garden/decor/artificial flora/artificial flowering plants', 'Home & Garden/Decor/Artificial Flora/Artificial Flowering Plants', 'Home'),
  ('home & garden/decor/artificial flora/artificial trees', 'Home & Garden/Decor/Artificial Flora/Artificial Trees', 'Home'),
  ('home & garden/decor/baskets', 'Home & Garden/Decor/Baskets', 'Home'),
  ('home & garden/decor/bird & wildlife feeders/bird feeders', 'Home & Garden/Decor/Bird & Wildlife Feeders/Bird Feeders', 'Home'),
  ('home & garden/decor/bird baths', 'Home & Garden/Decor/Bird Baths', 'Home'),
  ('home & garden/decor/clocks/wall clocks', 'Home & Garden/Decor/Clocks/Wall Clocks', 'Home'),
  ('home & garden/decor/decorative trays', 'Home & Garden/Decor/Decorative Trays', 'Home'),
  ('home & garden/decor/door mats', 'Home & Garden/Decor/Door Mats', 'Home'),
  ('home & garden/decor/fountains & ponds/fountains & waterfalls/fountains', 'Home & Garden/Decor/Fountains & Ponds/Fountains & Waterfalls/Fountains', 'Home'),
  ('home & garden/decor/home fragrance accessories/candle holders', 'Home & Garden/Decor/Home Fragrance Accessories/Candle Holders', 'Home'),
  ('home & garden/decor/home fragrances/air fresheners', 'Home & Garden/Decor/Home Fragrances/Air Fresheners', 'Home'),
  ('home & garden/decor/home fragrances/candles', 'Home & Garden/Decor/Home Fragrances/Candles', 'Home'),
  ('home & garden/decor/lawn ornaments & garden sculptures/garden sculptures', 'Home & Garden/Decor/Lawn Ornaments & Garden Sculptures/Garden Sculptures', 'Home'),
  ('home & garden/decor/mirrors', 'Home & Garden/Decor/Mirrors', 'Home'),
  ('home & garden/decor/rugs', 'Home & Garden/Decor/Rugs', 'Home'),
  ('home & garden/decor/window treatment accessories/curtain & drape rods', 'Home & Garden/Decor/Window Treatment Accessories/Curtain & Drape Rods', 'Home'),
  ('home & garden/decor/window treatment accessories/window treatment replacement parts/window rods', 'Home & Garden/Decor/Window Treatment Accessories/Window Treatment Replacement Parts/Window Rods', 'Home'),
  ('home & garden/decor/window treatments/curtains & drapes/curtains', 'Home & Garden/Decor/Window Treatments/Curtains & Drapes/Curtains', 'Home'),
  ('home & garden/decor/window treatments/window blinds & shades/blinds', 'Home & Garden/Decor/Window Treatments/Window Blinds & Shades/Blinds', 'Home'),
  ('home & garden/household appliance accessories/air purifier accessories/air purifier filters', 'Home & Garden/Household Appliance Accessories/Air Purifier Accessories/Air Purifier Filters', 'Electricals'),
  ('home & garden/household appliances/climate control appliances/air purifiers', 'Home & Garden/Household Appliances/Climate Control Appliances/Air Purifiers', 'Electricals'),
  ('home & garden/household appliances/climate control appliances/dehumidifiers', 'Home & Garden/Household Appliances/Climate Control Appliances/Dehumidifiers', 'Electricals'),
  ('home & garden/household appliances/climate control appliances/space heaters', 'Home & Garden/Household Appliances/Climate Control Appliances/Space Heaters', 'Electricals'),
  ('home & garden/household appliances/floor & steam cleaners/carpet steamers/multi-purpose steam cleaners', 'Home & Garden/Household Appliances/Floor & Steam Cleaners/Carpet Steamers/Multi-Purpose Steam Cleaners', 'Electricals'),
  ('home & garden/household appliances/floor & steam cleaners/floor cleaners', 'Home & Garden/Household Appliances/Floor & Steam Cleaners/Floor Cleaners', 'Electricals'),
  ('home & garden/household appliances/floor & steam cleaners/handheld steam cleaners', 'Home & Garden/Household Appliances/Floor & Steam Cleaners/Handheld Steam Cleaners', 'Electricals'),
  ('home & garden/household appliances/laundry appliances/garment steamers', 'Home & Garden/Household Appliances/Laundry Appliances/Garment Steamers', 'Electricals'),
  ('home & garden/household appliances/vacuums/canister vacs', 'Home & Garden/Household Appliances/Vacuums/Canister Vacs', 'Electricals'),
  ('home & garden/household appliances/vacuums/upright vacuums', 'Home & Garden/Household Appliances/Vacuums/Upright Vacuums', 'Electricals'),
  ('home & garden/household supplies/furniture floor protectors', 'Home & Garden/Household Supplies/Furniture Floor Protectors', 'Home'),
  ('home & garden/household supplies/household cleaning supplies/household cleaning products/descalers & decalcifiers', 'Home & Garden/Household Supplies/Household Cleaning Supplies/Household Cleaning Products/Descalers & Decalcifiers', 'Home'),
  ('home & garden/household supplies/household cleaning supplies/household cleaning products/dish detergent & soap', 'Home & Garden/Household Supplies/Household Cleaning Supplies/Household Cleaning Products/Dish Detergent & Soap', 'Home'),
  ('home & garden/household supplies/household cleaning supplies/household cleaning products/dishwasher cleaners/detergent removers', 'Home & Garden/Household Supplies/Household Cleaning Supplies/Household Cleaning Products/Dishwasher Cleaners/Detergent Removers', 'Home'),
  ('home & garden/household supplies/household cleaning supplies/household cleaning products/oven & grill cleaners', 'Home & Garden/Household Supplies/Household Cleaning Supplies/Household Cleaning Products/Oven & Grill Cleaners', 'Home'),
  ('home & garden/household supplies/household cleaning supplies/household cleaning products/washing machine cleaners', 'Home & Garden/Household Supplies/Household Cleaning Supplies/Household Cleaning Products/Washing Machine Cleaners', 'Home'),
  ('home & garden/household supplies/household cleaning supplies/mop heads & refills', 'Home & Garden/Household Supplies/Household Cleaning Supplies/Mop Heads & Refills', 'Home'),
  ('home & garden/household supplies/household cleaning supplies/mops', 'Home & Garden/Household Supplies/Household Cleaning Supplies/Mops', 'Home'),
  ('home & garden/household supplies/household cleaning supplies/scrub brushes', 'Home & Garden/Household Supplies/Household Cleaning Supplies/Scrub Brushes', 'Home'),
  ('home & garden/household supplies/laundry supplies/fabric softeners & dryer sheets/dryer sheets', 'Home & Garden/Household Supplies/Laundry Supplies/Fabric Softeners & Dryer Sheets/Dryer Sheets', 'Home'),
  ('home & garden/household supplies/laundry supplies/laundry detergent', 'Home & Garden/Household Supplies/Laundry Supplies/Laundry Detergent', 'Home'),
  ('home & garden/household supplies/pest control/pest control traps/live traps', 'Home & Garden/Household Supplies/Pest Control/Pest Control Traps/Live Traps', 'Home'),
  ('home & garden/household supplies/storage & organisation/clothing & closet storage/closet organisers & garment racks/garment racks', 'Home & Garden/Household Supplies/Storage & Organisation/Clothing & Closet Storage/Closet Organisers & Garment Racks/Garment Racks', 'Home'),
  ('home & garden/household supplies/storage & organisation/clothing & closet storage/shoe racks & organisers/shoe organisers', 'Home & Garden/Household Supplies/Storage & Organisation/Clothing & Closet Storage/Shoe Racks & Organisers/Shoe Organisers', 'Home'),
  ('home & garden/household supplies/storage & organisation/clothing & closet storage/shoe racks & organisers/shoe racks', 'Home & Garden/Household Supplies/Storage & Organisation/Clothing & Closet Storage/Shoe Racks & Organisers/Shoe Racks', 'Home'),
  ('home & garden/household supplies/storage & organisation/household storage containers', 'Home & Garden/Household Supplies/Storage & Organisation/Household Storage Containers', 'Home'),
  ('home & garden/household supplies/storage & organisation/household storage drawers', 'Home & Garden/Household Supplies/Storage & Organisation/Household Storage Drawers', 'Home'),
  ('home & garden/household supplies/waste containment/trash cans & wastebaskets/trash cans', 'Home & Garden/Household Supplies/Waste Containment/Trash Cans & Wastebaskets/Trash Cans', 'Home'),
  ('home & garden/kitchen & dining/cookware & bakeware/cookware/cookware sets', 'Home & Garden/Kitchen & Dining/Cookware & Bakeware/Cookware/Cookware Sets', 'Home'),
  ('home & garden/kitchen & dining/cookware & bakeware/cookware/dutch ovens', 'Home & Garden/Kitchen & Dining/Cookware & Bakeware/Cookware/Dutch Ovens', 'Home'),
  ('home & garden/kitchen & dining/cookware & bakeware/cookware/griddles & grill pans', 'Home & Garden/Kitchen & Dining/Cookware & Bakeware/Cookware/Griddles & Grill Pans', 'Home'),
  ('home & garden/kitchen & dining/cookware & bakeware/cookware/skillets & frying pans/frying pans', 'Home & Garden/Kitchen & Dining/Cookware & Bakeware/Cookware/Skillets & Frying Pans/Frying Pans', 'Home'),
  ('home & garden/kitchen & dining/cookware & bakeware/cookware/skillets & frying pans/skillets', 'Home & Garden/Kitchen & Dining/Cookware & Bakeware/Cookware/Skillets & Frying Pans/Skillets', 'Home'),
  ('home & garden/kitchen & dining/food storage/bread boxes & bags', 'Home & Garden/Kitchen & Dining/Food Storage/Bread Boxes & Bags', 'Home'),
  ('home & garden/kitchen & dining/food storage/food storage containers', 'Home & Garden/Kitchen & Dining/Food Storage/Food Storage Containers', 'Home'),
  ('home & garden/kitchen & dining/kitchen appliance accessories/cooktop, oven & range accessories/racks', 'Home & Garden/Kitchen & Dining/Kitchen Appliance Accessories/Cooktop, Oven & Range Accessories/Racks', 'Electricals'),
  ('home & garden/kitchen & dining/kitchen appliances/air fryers', 'Home & Garden/Kitchen & Dining/Kitchen Appliances/Air Fryers', 'Electricals'),
  ('home & garden/kitchen & dining/kitchen appliances/breadmakers', 'Home & Garden/Kitchen & Dining/Kitchen Appliances/Breadmakers', 'Electricals'),
  ('home & garden/kitchen & dining/kitchen appliances/coffee makers & espresso machines/espresso machines', 'Home & Garden/Kitchen & Dining/Kitchen Appliances/Coffee Makers & Espresso Machines/Espresso Machines', 'Electricals'),
  ('home & garden/kitchen & dining/kitchen appliances/deep fryers', 'Home & Garden/Kitchen & Dining/Kitchen Appliances/Deep Fryers', 'Electricals'),
  ('home & garden/kitchen & dining/kitchen appliances/food dehydrators', 'Home & Garden/Kitchen & Dining/Kitchen Appliances/Food Dehydrators', 'Electricals'),
  ('home & garden/kitchen & dining/kitchen appliances/food grinders & mills/food grinders', 'Home & Garden/Kitchen & Dining/Kitchen Appliances/Food Grinders & Mills/Food Grinders', 'Electricals'),
  ('home & garden/kitchen & dining/kitchen appliances/food mixers & blenders/food blenders', 'Home & Garden/Kitchen & Dining/Kitchen Appliances/Food Mixers & Blenders/Food Blenders', 'Electricals'),
  ('home & garden/kitchen & dining/kitchen appliances/food mixers & blenders/food mixers', 'Home & Garden/Kitchen & Dining/Kitchen Appliances/Food Mixers & Blenders/Food Mixers', 'Electricals'),
  ('home & garden/kitchen & dining/kitchen appliances/frozen drink makers', 'Home & Garden/Kitchen & Dining/Kitchen Appliances/Frozen Drink Makers', 'Electricals'),
  ('home & garden/kitchen & dining/kitchen appliances/ice makers', 'Home & Garden/Kitchen & Dining/Kitchen Appliances/Ice Makers', 'Electricals'),
  ('home & garden/kitchen & dining/kitchen appliances/juicers', 'Home & Garden/Kitchen & Dining/Kitchen Appliances/Juicers', 'Electricals'),
  ('home & garden/kitchen & dining/kitchen appliances/refrigerators', 'Home & Garden/Kitchen & Dining/Kitchen Appliances/Refrigerators', 'Electricals'),
  ('home & garden/kitchen & dining/kitchen tools & utensils/cutting boards', 'Home & Garden/Kitchen & Dining/Kitchen Tools & Utensils/Cutting Boards', 'Home'),
  ('home & garden/kitchen & dining/kitchen tools & utensils/dish racks & drain boards/dish racks', 'Home & Garden/Kitchen & Dining/Kitchen Tools & Utensils/Dish Racks & Drain Boards/Dish Racks', 'Home'),
  ('home & garden/kitchen & dining/kitchen tools & utensils/kitchen organisers/kitchen cabinet organisers', 'Home & Garden/Kitchen & Dining/Kitchen Tools & Utensils/Kitchen Organisers/Kitchen Cabinet Organisers', 'Home'),
  ('home & garden/kitchen & dining/kitchen tools & utensils/kitchen organisers/kitchen utensil holders & racks/kitchen utensil racks', 'Home & Garden/Kitchen & Dining/Kitchen Tools & Utensils/Kitchen Organisers/Kitchen Utensil Holders & Racks/Kitchen Utensil Racks', 'Home'),
  ('home & garden/kitchen & dining/kitchen tools & utensils/salad dressing mixers & shakers/mixers', 'Home & Garden/Kitchen & Dining/Kitchen Tools & Utensils/Salad Dressing Mixers & Shakers/Mixers', 'Home'),
  ('home & garden/kitchen & dining/kitchen tools & utensils/sink caddies', 'Home & Garden/Kitchen & Dining/Kitchen Tools & Utensils/Sink Caddies', 'Home'),
  ('home & garden/kitchen & dining/tableware/drinkware/tumblers', 'Home & Garden/Kitchen & Dining/Tableware/Drinkware/Tumblers', 'Home'),
  ('home & garden/kitchen & dining/tableware/serveware/serving trays', 'Home & Garden/Kitchen & Dining/Tableware/Serveware/Serving Trays', 'Home'),
  ('home & garden/lawn & garden/gardening/gardening tools/pruning shears', 'Home & Garden/Lawn & Garden/Gardening/Gardening Tools/Pruning Shears', 'Outdoor'),
  ('home & garden/lawn & garden/gardening/gardening tools/wheelbarrows', 'Home & Garden/Lawn & Garden/Gardening/Gardening Tools/Wheelbarrows', 'Outdoor'),
  ('home & garden/lawn & garden/gardening/plant cages & supports/plant cages', 'Home & Garden/Lawn & Garden/Gardening/Plant Cages & Supports/Plant Cages', 'Outdoor'),
  ('home & garden/lawn & garden/gardening/plant stands', 'Home & Garden/Lawn & Garden/Gardening/Plant Stands', 'Outdoor'),
  ('home & garden/lawn & garden/gardening/pots & planters/planters', 'Home & Garden/Lawn & Garden/Gardening/Pots & Planters/Planters', 'Outdoor'),
  ('home & garden/lawn & garden/gardening/pots & planters/pots', 'Home & Garden/Lawn & Garden/Gardening/Pots & Planters/Pots', 'Outdoor'),
  ('home & garden/lawn & garden/outdoor living/hammocks', 'Home & Garden/Lawn & Garden/Outdoor Living/Hammocks', 'Outdoor'),
  ('home & garden/lawn & garden/outdoor living/outdoor structures/garden arches, trellises, arbours & pergolas/trellises', 'Home & Garden/Lawn & Garden/Outdoor Living/Outdoor Structures/Garden Arches, Trellises, Arbours & Pergolas/Trellises', 'Outdoor'),
  ('home & garden/lawn & garden/outdoor power equipment/chainsaws', 'Home & Garden/Lawn & Garden/Outdoor Power Equipment/Chainsaws', 'Outdoor'),
  ('home & garden/lawn & garden/outdoor power equipment/lawn aerators & dethatchers/lawn aerators', 'Home & Garden/Lawn & Garden/Outdoor Power Equipment/Lawn Aerators & Dethatchers/Lawn Aerators', 'Outdoor'),
  ('home & garden/lawn & garden/outdoor power equipment/pressure washers', 'Home & Garden/Lawn & Garden/Outdoor Power Equipment/Pressure Washers', 'Outdoor'),
  ('home & garden/lawn & garden/watering & irrigation/garden hoses', 'Home & Garden/Lawn & Garden/Watering & Irrigation/Garden Hoses', 'Outdoor'),
  ('home & garden/lawn & garden/watering & irrigation/watering cans', 'Home & Garden/Lawn & Garden/Watering & Irrigation/Watering Cans', 'Outdoor'),
  ('home & garden/lighting accessories/lamp shades', 'Home & Garden/Lighting Accessories/Lamp Shades', 'Home'),
  ('home & garden/lighting/lamps/floor lamps', 'Home & Garden/Lighting/Lamps/Floor Lamps', 'Home'),
  ('home & garden/lighting/lighting fixtures/ceiling light fixtures', 'Home & Garden/Lighting/Lighting Fixtures/Ceiling Light Fixtures', 'Home'),
  ('home & garden/linens & bedding/bedding/blankets', 'Home & Garden/Linens & Bedding/Bedding/Blankets', 'Home'),
  ('home & garden/linens & bedding/bedding/mattress protectors/mattress encasements', 'Home & Garden/Linens & Bedding/Bedding/Mattress Protectors/Mattress Encasements', 'Home'),
  ('home & garden/linens & bedding/bedding/mattress protectors/mattress pads', 'Home & Garden/Linens & Bedding/Bedding/Mattress Protectors/Mattress Pads', 'Home'),
  ('home & garden/linens & bedding/bedding/pillows', 'Home & Garden/Linens & Bedding/Bedding/Pillows', 'Home'),
  ('home & garden/linens & bedding/bedding/quilts & comforters', 'Home & Garden/Linens & Bedding/Bedding/Quilts & Comforters', 'Home'),
  ('home & garden/parasols & rain umbrellas/parasols', 'Home & Garden/Parasols & Rain Umbrellas/Parasols', 'Outdoor'),
  ('home & garden/pool & spa/pool & spa accessories/pool toys/pool games', 'Home & Garden/Pool & Spa/Pool & Spa Accessories/Pool Toys/Pool Games', 'Sports & Leisure'),
  ('luggage & bags/backpacks/school backpacks', 'Luggage & Bags/Backpacks/School Backpacks', 'Sports & Leisure'),
  ('luggage & bags/suitcases/kids'' suitcases', 'Luggage & Bags/Suitcases/Kids'' Suitcases', 'Sports & Leisure'),
  ('luggage & bags/suitcases/suitcase travel sets', 'Luggage & Bags/Suitcases/Suitcase Travel Sets', 'Sports & Leisure'),
  ('office supplies/filing & organisation/desk organisers/desktop organisers', 'Office Supplies/Filing & Organisation/Desk Organisers/Desktop Organisers', 'Home'),
  ('office supplies/filing & organisation/desk organisers/drawer organisers', 'Office Supplies/Filing & Organisation/Desk Organisers/Drawer Organisers', 'Home'),
  ('office supplies/office & chair mats/chair mats', 'Office Supplies/Office & Chair Mats/Chair Mats', 'Home'),
  ('office supplies/presentation supplies/display boards/bulletin boards', 'Office Supplies/Presentation Supplies/Display Boards/Bulletin Boards', 'Home'),
  ('office supplies/presentation supplies/dry-erase boards', 'Office Supplies/Presentation Supplies/Dry-Erase Boards', 'Home'),
  ('sporting goods/athletics/basketball/basketball hoops', 'Sporting Goods/Athletics/Basketball/Basketball Hoops', 'Sports & Leisure'),
  ('sporting goods/athletics/boxing & martial arts/boxing & martial arts training equipment/punching & training bags/punching & training punch pads', 'Sporting Goods/Athletics/Boxing & Martial Arts/Boxing & Martial Arts Training Equipment/Punching & Training Bags/Punching & Training Punch Pads', 'Sports & Leisure'),
  ('sporting goods/athletics/general purpose athletic equipment/gym mats', 'Sporting Goods/Athletics/General Purpose Athletic Equipment/Gym Mats', 'Sports & Leisure'),
  ('sporting goods/athletics/general purpose athletic equipment/speed & agility ladders & hurdles', 'Sporting Goods/Athletics/General Purpose Athletic Equipment/Speed & Agility Ladders & Hurdles', 'Sports & Leisure'),
  ('sporting goods/athletics/tennis/tennis rackets', 'Sporting Goods/Athletics/Tennis/Tennis Rackets', 'Sports & Leisure'),
  ('sporting goods/athletics/track & field/track & field training aids/track & field resistance bands', 'Sporting Goods/Athletics/Track & Field/Track & Field Training Aids/Track & Field Resistance Bands', 'Sports & Leisure'),
  ('sporting goods/athletics/track & field/track hurdles', 'Sporting Goods/Athletics/Track & Field/Track Hurdles', 'Sports & Leisure'),
  ('sporting goods/fitness & general exercise equipment/ab wheels & rollers/ab wheels', 'Sporting Goods/Fitness & General Exercise Equipment/Ab Wheels & Rollers/Ab Wheels', 'Sports & Leisure'),
  ('sporting goods/fitness & general exercise equipment/balance trainers/balance boards', 'Sporting Goods/Fitness & General Exercise Equipment/Balance Trainers/Balance Boards', 'Sports & Leisure'),
  ('sporting goods/fitness & general exercise equipment/cardio/cardio machine accessories & parts/exercise bike accessories & parts/exercise bike stands', 'Sporting Goods/Fitness & General Exercise Equipment/Cardio/Cardio Machine Accessories & Parts/Exercise Bike Accessories & Parts/Exercise Bike Stands', 'Sports & Leisure'),
  ('sporting goods/fitness & general exercise equipment/cardio/cardio machines/elliptical trainers/electromagnetic elliptical trainers', 'Sporting Goods/Fitness & General Exercise Equipment/Cardio/Cardio Machines/Elliptical Trainers/Electromagnetic Elliptical Trainers', 'Sports & Leisure'),
  ('sporting goods/fitness & general exercise equipment/cardio/cardio machines/exercise bikes/upright exercise bikes', 'Sporting Goods/Fitness & General Exercise Equipment/Cardio/Cardio Machines/Exercise Bikes/Upright Exercise Bikes', 'Sports & Leisure'),
  ('sporting goods/fitness & general exercise equipment/cardio/cardio machines/stair climbers & steppers/stair steppers', 'Sporting Goods/Fitness & General Exercise Equipment/Cardio/Cardio Machines/Stair Climbers & Steppers/Stair Steppers', 'Sports & Leisure'),
  ('sporting goods/fitness & general exercise equipment/cardio/cardio machines/treadmills', 'Sporting Goods/Fitness & General Exercise Equipment/Cardio/Cardio Machines/Treadmills', 'Sports & Leisure'),
  ('sporting goods/fitness & general exercise equipment/cardio/jump ropes', 'Sporting Goods/Fitness & General Exercise Equipment/Cardio/Jump Ropes', 'Sports & Leisure'),
  ('sporting goods/fitness & general exercise equipment/exercise benches', 'Sporting Goods/Fitness & General Exercise Equipment/Exercise Benches', 'Sports & Leisure'),
  ('sporting goods/fitness & general exercise equipment/exercise machine & equipment sets', 'Sporting Goods/Fitness & General Exercise Equipment/Exercise Machine & Equipment Sets', 'Sports & Leisure'),
  ('sporting goods/fitness & general exercise equipment/hand exercisers', 'Sporting Goods/Fitness & General Exercise Equipment/Hand Exercisers', 'Sports & Leisure'),
  ('sporting goods/fitness & general exercise equipment/push up & pull up bars', 'Sporting Goods/Fitness & General Exercise Equipment/Push Up & Pull Up Bars', 'Sports & Leisure'),
  ('sporting goods/fitness & general exercise equipment/weight lifting/free weight accessories/barbells & weightlifting bars', 'Sporting Goods/Fitness & General Exercise Equipment/Weight Lifting/Free Weight Accessories/Barbells & Weightlifting Bars', 'Sports & Leisure'),
  ('sporting goods/fitness & general exercise equipment/weight lifting/free weight accessories/free weight storage racks', 'Sporting Goods/Fitness & General Exercise Equipment/Weight Lifting/Free Weight Accessories/Free Weight Storage Racks', 'Sports & Leisure'),
  ('sporting goods/fitness & general exercise equipment/weight lifting/free weights, dumbbells & kettlebells/dumbbells', 'Sporting Goods/Fitness & General Exercise Equipment/Weight Lifting/Free Weights, Dumbbells & Kettlebells/Dumbbells', 'Sports & Leisure'),
  ('sporting goods/fitness & general exercise equipment/weight lifting/weight lifting belts', 'Sporting Goods/Fitness & General Exercise Equipment/Weight Lifting/Weight Lifting Belts', 'Sports & Leisure'),
  ('sporting goods/fitness & general exercise equipment/weight lifting/weight lifting machines & racks/weight lifting racks', 'Sporting Goods/Fitness & General Exercise Equipment/Weight Lifting/Weight Lifting Machines & Racks/Weight Lifting Racks', 'Sports & Leisure'),
  ('sporting goods/fitness & general exercise equipment/weighted clothing/weighted vests', 'Sporting Goods/Fitness & General Exercise Equipment/Weighted Clothing/Weighted Vests', 'Sports & Leisure'),
  ('sporting goods/outdoor recreation/camping & hiking/camp furniture/air mattresses', 'Sporting Goods/Outdoor Recreation/Camping & Hiking/Camp Furniture/Air Mattresses', 'Sports & Leisure'),
  ('sporting goods/outdoor recreation/camping & hiking/camp furniture/cots', 'Sporting Goods/Outdoor Recreation/Camping & Hiking/Camp Furniture/Cots', 'Sports & Leisure'),
  ('sporting goods/outdoor recreation/camping & hiking/hiking poles', 'Sporting Goods/Outdoor Recreation/Camping & Hiking/Hiking Poles', 'Sports & Leisure'),
  ('sporting goods/outdoor recreation/camping & hiking/sleeping bags', 'Sporting Goods/Outdoor Recreation/Camping & Hiking/Sleeping Bags', 'Sports & Leisure'),
  ('sporting goods/outdoor recreation/camping & hiking/sleeping pads', 'Sporting Goods/Outdoor Recreation/Camping & Hiking/Sleeping Pads', 'Sports & Leisure'),
  ('sporting goods/outdoor recreation/cycling/bicycle accessories/bicycle locks/bicycle cable locks', 'Sporting Goods/Outdoor Recreation/Cycling/Bicycle Accessories/Bicycle Locks/Bicycle Cable Locks', 'Sports & Leisure'),
  ('sporting goods/outdoor recreation/cycling/bicycle accessories/bicycle tire repair supplies & kits/bicycle tire repair stands', 'Sporting Goods/Outdoor Recreation/Cycling/Bicycle Accessories/Bicycle Tire Repair Supplies & Kits/Bicycle Tire Repair Stands', 'Sports & Leisure'),
  ('sporting goods/outdoor recreation/golf/golf bags', 'Sporting Goods/Outdoor Recreation/Golf/Golf Bags', 'Sports & Leisure'),
  ('sporting goods/outdoor recreation/golf/golf training aids/golf putting mats', 'Sporting Goods/Outdoor Recreation/Golf/Golf Training Aids/Golf Putting Mats', 'Sports & Leisure'),
  ('sporting goods/outdoor recreation/outdoor games/badminton/badminton rackets & sets/badminton racket sets', 'Sporting Goods/Outdoor Recreation/Outdoor Games/Badminton/Badminton Rackets & Sets/Badminton Racket Sets', 'Sports & Leisure'),
  ('sporting goods/outdoor recreation/riding scooters/kick scooters', 'Sporting Goods/Outdoor Recreation/Riding Scooters/Kick Scooters', 'Sports & Leisure'),
  ('toys & games/outdoor play equipment/slides', 'Toys & Games/Outdoor Play Equipment/Slides', 'Toys'),
  ('toys & games/outdoor play equipment/trampolines', 'Toys & Games/Outdoor Play Equipment/Trampolines', 'Toys'),
  ('toys & games/toys/bath toys/floating bath toys', 'Toys & Games/Toys/Bath Toys/Floating Bath Toys', 'Toys'),
  ('toys & games/toys/executive toys/magnet toys', 'Toys & Games/Toys/Executive Toys/Magnet Toys', 'Toys'),
  ('toys & games/toys/sports toys/fitness toys/mini trampolines', 'Toys & Games/Toys/Sports Toys/Fitness Toys/Mini Trampolines', 'Toys')
on conflict (category_key) do update set
  tesco_category = excluded.tesco_category,
  level_1 = excluded.level_1,
  updated_at = now();

comment on table public.promotion_tesco_category_mappings is
  'Shared Tesco catalogue category to fixed nomination Level 1 mappings.';
